<?php

/**
 * @file
 * Contains facets_demo.module.
 */

/**
 * Implements hook_preprocess_views_view().
 */
function facets_demo_preprocess_views_view(&$variables) {
  $view = $variables['view'];
  if ($view->id() === 'movies' && $view->current_display === 'page_1') {
    $variables['#attached']['library'][] = 'facets_demo/styling';
  }
}

/**
 * Implements hook_theme().
 */
function facets_demo_theme($existing, $type, $theme, $path) {
  return [
    'views_view__movies' => [
      'base hook' => 'views_view',
      'template' => 'views-view--movies',
      'path' => $path . '/templates',
    ],
  ];
}
