_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  authorization: 0
  auto_entitylabel: 0
  automated_cron: 0
  ban: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  bulk_update_fields: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  content_moderation: 0
  contextual: 0
  css_editor: 0
  csv_serialization: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  facets: 0
  facets_rest: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  http_response_headers: 0
  image: 0
  jwt: 0
  jwt_auth_consumer: 0
  jwt_auth_issuer: 0
  key: 0
  layout_builder: 0
  layout_discovery: 0
  ldap_authentication: 0
  ldap_authorization: 0
  ldap_query: 0
  ldap_servers: 0
  ldap_user: 0
  link: 0
  menu_ui: 0
  moderated_content_bulk_publish: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  prepopulate: 0
  quickedit: 0
  quip: 0
  rdf: 0
  redirect_after_login: 0
  rest: 0
  restui: 0
  search_api: 0
  search_api_db: 0
  search_api_db_defaults: 0
  serialization: 0
  system: 0
  tac_lite_create: 0
  taxonomy: 0
  taxonomy_unique: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  typed_data: 0
  update: 0
  user: 0
  user_current_paths: 0
  views_base_url: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_field_view: 0
  views_taxonomy_term_name_depth: 0
  views_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  externalauth: 10
  views: 10
  tac_lite: 100
  standard: 1000
theme:
  bootstrap: 0
  seven: 0
profile: standard
