_core:
  default_config_hash: ALaJtTMWaPkrzRKrWM1z4u7BslSR_0tTzlGXfeZPhDQ
include_invalid_paths: true
excluded_paths: "admin\r\noverview\r\ntac_lite\r\nadd\r\npeople\r\nupdates\r\nupdate\r\ncollections"
replaced_titles: ''
custom_paths: ''
include_home_segment: false
home_segment_title: Home
home_segment_keep: false
include_title_segment: false
title_from_page_when_available: false
title_segment_as_link: false
segments_separator: null
use_menu_title_as_fallback: false
remove_repeated_segments: true
language_path_prefix_as_segment: false
absolute_paths: false
hide_single_home_item: true
add_structured_data_json_ld: false
capitalizator_ignored_words: {  }
capitalizator_forced_words: {  }
capitalizator_forced_words_case_sensitivity: false
capitalizator_forced_words_first_letter: false
follow_redirects: true
