_core:
  default_config_hash: xGaDFlyXTmhzluhiRhEx58v_3Fu-nMhCzEBF8K4eqHU
drupalAcctProvisionServer: tciabeta
ldapEntryProvisionServer: null
drupalAcctProvisionTriggers:
  - drupal_on_login
ldapEntryProvisionTriggers: {  }
orphanedDrupalAcctBehavior: ldap_user_orphan_email
orphanedDrupalAcctReportingInbox: ''
orphanedCheckQty: 100
orphanedAccountCheckInterval: weekly
userConflictResolve: resolve
manualAccountConflict: conflict_reject
acctCreation: ldap_behaviour
disableAdminPasswordField: false
userUpdateCronQuery: none
userUpdateCronInterval: daily
ldapUserSyncMappings:
  drupal: {  }
