_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 533fc7cc-82dd-46b2-8d63-160785138977
name: 'QuIP - Quantitative Imaging in Pathology'
mail: erich.bremer@stonybrook.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /imagesearch
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
