<?php

/**
 * @file
 * Contains computed_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function computed_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the computed_field module.
    case 'help.page.computed_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines a field type that allows values to be &quot;computed&quot; via PHP code.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function computed_field_theme() {
  $theme = [];

  return $theme;
}
